name: Release
on:
  push:
    tags: ["v*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm build
      - name: Verify tarball contents
        run: |
          pnpm pack --dry-run | tee tarball.txt
          grep -q "docs/" tarball.txt && { echo "Docs vazando!"; exit 1; } || echo "OK: pacote limpo."
      - run: pnpm publish --access public --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 